const PL_TEAM_CODE: Record<string, string> = {
  Arsenal: 'ARS',
  'Aston Villa': 'AVL',
  'AFC Bournemouth': 'BOU',
  Bournemouth: 'BOU',
  Brentford: 'BRE',
  'Brighton & Hove Albion': 'BHA',
  Brighton: 'BHA',
  Chelsea: 'CHE',
  Coventry: 'COV',
  'Crystal Palace': 'CRY',
  Everton: 'EVE',
  Fulham: 'FUL',
  'Ipswich Town': 'IPS',
  Ipswich: 'IPS',
  'Leicester City': 'LEI',
  Liverpool: 'LIV',
  'Manchester City': 'MCI',
  'Manchester United': 'MUN',
  'Newcastle United': 'NEW',
  Newcastle: 'NEW',
  'Nottingham Forest': 'NFO',
  Southampton: 'SOU',
  Sunderland: 'SUN',
  'Tottenham Hotspur': 'TOT',
  Tottenham: 'TOT',
  'Hull City': 'HUL',
  Leeds: 'LEE',
  'West Ham United': 'WHU',
  'Wolverhampton Wanderers': 'WOL',
};

export { PL_TEAM_CODE };
