const PL_TEAM_KOREAN_NAME: Record<string, string> = {
  Arsenal: '아스널',
  'Aston Villa': '애스턴 빌라',
  Bournemouth: '본머스',
  Brentford: '브렌트퍼드',
  'Brighton & Hove Albion': '브라이튼 앤 호브 알비온',
  Brighton: '브라이튼 앤 호브 알비온',
  Coventry: '코번트리',
  Chelsea: '첼시',
  'Crystal Palace': '크리스털 팰리스',
  Everton: '에버턴',
  Fulham: '풀럼',
  'Ipswich Town': '입스위치 타운',
  Ipswich: '입스위치 타운',
  'Leicester City': '레스터 시티',
  Liverpool: '리버풀',
  'Manchester City': '맨체스터 시티',
  'Manchester United': '맨체스터 유나이티드',
  'Newcastle United': '뉴캐슬 유나이티드',
  Newcastle: '뉴캐슬 유나이티드',
  'Nottingham Forest': '노팅엄 포레스트',
  Southampton: '사우샘프턴',
  'Tottenham Hotspur': '토트넘 홋스퍼',
  Tottenham: '토트넘 홋스퍼',
  'West Ham United': '웨스트햄 유나이티드',
  'Wolverhampton Wanderers': '울버햄튼 원더러스',
  Sunderland: '선덜랜드',
  'Hull City': '헐 시티',
  Leeds: '리즈 유나이티드',
};

export { PL_TEAM_KOREAN_NAME };
