/**
 * Manchester United Hub — player detail page mock data.
 *
 * Reconciled 1:1 against the design source's `window.PLAYERS`
 * (claude_design project 34f9fec0-0627-49ff-839c-fc645186091d,
 * `players-data.js`). Identity/bio/career/status values below are copied
 * verbatim from that file — do not hand-edit text/numbers here without
 * re-checking the source.
 *
 * `radar`/`ovr` are NOT recomputed at runtime: the source derives them once
 * at module-load time from a `RATINGS` lookup table + position-based axis
 * labels (`OUTFIELD_AXES` / `GK_AXES`), then `Math.round(sum/6)` for `ovr`.
 * Every player below has an explicit `RATINGS` entry in the source (the
 * `POS_DEFAULT` fallback is never exercised for this roster), so the
 * pre-computed values here reproduce that algorithm exactly — see
 * result-ST-001.md for the reconciliation script/output.
 *
 * No imports from e_entities / d_features / app/api (FSD 의존 방향 — plan.json
 * architecture.standards).
 */

import type { PlayerDetail } from './types';

// ───────── Current first team ─────────

export const players: PlayerDetail[] = [
  {
    id: 'bruno',
    num: 8,
    nm: '브루누 페르난데스',
    en: 'Bruno Fernandes',
    pos: 'MF',
    nat: '포르투갈',
    flag: 'pt',
    years: '2020–현재',
    dob: '1994.09.08',
    age: 31,
    birth: '마이아, 포르투갈',
    height: 179,
    weight: 69,
    foot: '오른발',
    joined: '2020.01.30',
    left: null,
    career: { apps: 290, goals: 84, assists: 71 },
    trophies: 2,
    status: 'active',
    squad: '1군',
    captain: true,
    radar: [
      { k: '슈팅', v: 82 },
      { k: '패스', v: 88 },
      { k: '드리블', v: 80 },
      { k: '스피드', v: 74 },
      { k: '수비', v: 66 },
      { k: '피지컬', v: 75 },
    ],
    ovr: 78,
  },
  {
    id: 'rashford',
    num: 10,
    nm: '마커스 래시포드',
    en: 'Marcus Rashford',
    pos: 'FW',
    nat: '잉글랜드',
    flag: 'gb',
    years: '2015–현재',
    dob: '1997.10.31',
    age: 28,
    birth: '맨체스터, 잉글랜드',
    height: 185,
    weight: 70,
    foot: '오른발',
    joined: '2015.02.27',
    left: null,
    career: { apps: 426, goals: 138, assists: 79 },
    trophies: 4,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '슈팅', v: 83 },
      { k: '패스', v: 72 },
      { k: '드리블', v: 85 },
      { k: '스피드', v: 90 },
      { k: '수비', v: 42 },
      { k: '피지컬', v: 75 },
    ],
    ovr: 75,
  },
  {
    id: 'hojlund',
    num: 11,
    nm: '라스무스 회일룬',
    en: 'Rasmus Højlund',
    pos: 'FW',
    nat: '덴마크',
    flag: 'dk',
    years: '2023–현재',
    dob: '2003.02.04',
    age: 23,
    birth: '코펜하겐, 덴마크',
    height: 191,
    weight: 80,
    foot: '오른발',
    joined: '2023.08.05',
    left: null,
    career: { apps: 86, goals: 26, assists: 6 },
    trophies: 1,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '슈팅', v: 80 },
      { k: '패스', v: 64 },
      { k: '드리블', v: 74 },
      { k: '스피드', v: 86 },
      { k: '수비', v: 40 },
      { k: '피지컬', v: 82 },
    ],
    ovr: 71,
  },
  {
    id: 'mainoo',
    num: 37,
    nm: '코비 메이누',
    en: 'Kobbie Mainoo',
    pos: 'MF',
    nat: '잉글랜드',
    flag: 'gb',
    years: '2023–현재',
    dob: '2005.04.19',
    age: 21,
    birth: '스톡포트, 잉글랜드',
    height: 175,
    weight: 70,
    foot: '오른발',
    joined: '2023.11.01',
    left: null,
    career: { apps: 64, goals: 5, assists: 3 },
    trophies: 1,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '슈팅', v: 70 },
      { k: '패스', v: 80 },
      { k: '드리블', v: 82 },
      { k: '스피드', v: 76 },
      { k: '수비', v: 72 },
      { k: '피지컬', v: 70 },
    ],
    ovr: 75,
  },
  {
    id: 'martinez',
    num: 6,
    nm: '리산드로 마르티네스',
    en: 'Lisandro Martínez',
    pos: 'DF',
    nat: '아르헨티나',
    flag: 'ar',
    years: '2022–현재',
    dob: '1998.01.18',
    age: 28,
    birth: '구알레과이, 아르헨티나',
    height: 175,
    weight: 77,
    foot: '왼발',
    joined: '2022.07.27',
    left: null,
    career: { apps: 92, goals: 2, assists: 1 },
    trophies: 2,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '슈팅', v: 45 },
      { k: '패스', v: 78 },
      { k: '드리블', v: 70 },
      { k: '스피드', v: 76 },
      { k: '수비', v: 86 },
      { k: '피지컬', v: 80 },
    ],
    ovr: 73,
  },
  {
    id: 'onana',
    num: 24,
    nm: '안드레 오나나',
    en: 'André Onana',
    pos: 'GK',
    nat: '카메룬',
    flag: 'cm',
    years: '2023–현재',
    dob: '1996.04.02',
    age: 30,
    birth: '은콜은공, 카메룬',
    height: 190,
    weight: 92,
    foot: '오른발',
    joined: '2023.07.20',
    left: null,
    career: { apps: 102, goals: 0, assists: 1 },
    trophies: 1,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '반응', v: 85 },
      { k: '핸들링', v: 82 },
      { k: '킥력', v: 86 },
      { k: '위치선정', v: 83 },
      { k: '민첩성', v: 84 },
      { k: '공중장악', v: 80 },
    ],
    ovr: 83,
  },
  {
    id: 'dalot',
    num: 20,
    nm: '디오구 달롯',
    en: 'Diogo Dalot',
    pos: 'DF',
    nat: '포르투갈',
    flag: 'pt',
    years: '2018–현재',
    dob: '1999.03.18',
    age: 27,
    birth: '브라가, 포르투갈',
    height: 183,
    weight: 76,
    foot: '오른발',
    joined: '2018.06.06',
    left: null,
    career: { apps: 248, goals: 12, assists: 14 },
    trophies: 2,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '슈팅', v: 60 },
      { k: '패스', v: 76 },
      { k: '드리블', v: 78 },
      { k: '스피드', v: 84 },
      { k: '수비', v: 80 },
      { k: '피지컬', v: 76 },
    ],
    ovr: 76,
  },
  {
    id: 'shaw',
    num: 23,
    nm: '루크 쇼',
    en: 'Luke Shaw',
    pos: 'DF',
    nat: '잉글랜드',
    flag: 'gb',
    years: '2014–현재',
    dob: '1995.07.12',
    age: 30,
    birth: '킹스턴, 잉글랜드',
    height: 185,
    weight: 75,
    foot: '왼발',
    joined: '2014.06.27',
    left: null,
    career: { apps: 280, goals: 8, assists: 26 },
    trophies: 3,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '슈팅', v: 55 },
      { k: '패스', v: 80 },
      { k: '드리블', v: 75 },
      { k: '스피드', v: 80 },
      { k: '수비', v: 82 },
      { k: '피지컬', v: 78 },
    ],
    ovr: 75,
  },
  {
    id: 'casemiro',
    num: 18,
    nm: '카세미루',
    en: 'Casemiro',
    pos: 'MF',
    nat: '브라질',
    flag: 'br',
    years: '2022–현재',
    dob: '1992.02.23',
    age: 34,
    birth: '상조세두스캄푸스, 브라질',
    height: 185,
    weight: 84,
    foot: '오른발',
    joined: '2022.08.22',
    left: null,
    career: { apps: 108, goals: 11, assists: 7 },
    trophies: 2,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '슈팅', v: 68 },
      { k: '패스', v: 78 },
      { k: '드리블', v: 68 },
      { k: '스피드', v: 60 },
      { k: '수비', v: 86 },
      { k: '피지컬', v: 86 },
    ],
    ovr: 74,
  },
  {
    id: 'deligt',
    num: 4,
    nm: '마테이스 더 리흐트',
    en: 'Matthijs de Ligt',
    pos: 'DF',
    nat: '네덜란드',
    flag: 'nl',
    years: '2024–현재',
    dob: '1999.08.12',
    age: 26,
    birth: '레이던, 네덜란드',
    height: 189,
    weight: 89,
    foot: '오른발',
    joined: '2024.08.10',
    left: null,
    career: { apps: 42, goals: 2, assists: 1 },
    trophies: 0,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '슈팅', v: 48 },
      { k: '패스', v: 76 },
      { k: '드리블', v: 64 },
      { k: '스피드', v: 74 },
      { k: '수비', v: 87 },
      { k: '피지컬', v: 85 },
    ],
    ovr: 72,
  },
  {
    id: 'garnacho',
    num: 17,
    nm: '알레한드로 가르나초',
    en: 'Alejandro Garnacho',
    pos: 'FW',
    nat: '아르헨티나',
    flag: 'ar',
    years: '2020–현재',
    dob: '2004.07.01',
    age: 21,
    birth: '마드리드, 스페인',
    height: 180,
    weight: 73,
    foot: '오른발',
    joined: '2020.10.01',
    left: null,
    career: { apps: 144, goals: 26, assists: 18 },
    trophies: 1,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '슈팅', v: 78 },
      { k: '패스', v: 70 },
      { k: '드리블', v: 86 },
      { k: '스피드', v: 91 },
      { k: '수비', v: 38 },
      { k: '피지컬', v: 68 },
    ],
    ovr: 72,
  },
  {
    id: 'mount',
    num: 7,
    nm: '메이슨 마운트',
    en: 'Mason Mount',
    pos: 'MF',
    nat: '잉글랜드',
    flag: 'gb',
    years: '2023–현재',
    dob: '1999.01.10',
    age: 27,
    birth: '포츠머스, 잉글랜드',
    height: 178,
    weight: 70,
    foot: '오른발',
    joined: '2023.07.05',
    left: null,
    career: { apps: 44, goals: 3, assists: 2 },
    trophies: 1,
    status: 'active',
    squad: '1군',
    radar: [
      { k: '슈팅', v: 76 },
      { k: '패스', v: 82 },
      { k: '드리블', v: 80 },
      { k: '스피드', v: 76 },
      { k: '수비', v: 70 },
      { k: '피지컬', v: 70 },
    ],
    ovr: 76,
  },

  // ───────── Legends (retired) ─────────

  {
    id: 'rooney',
    num: 10,
    nm: '웨인 루니',
    en: 'Wayne Rooney',
    pos: 'FW',
    nat: '잉글랜드',
    flag: 'gb',
    years: '2004–2017',
    dob: '1985.10.24',
    age: 40,
    birth: '리버풀, 잉글랜드',
    height: 176,
    weight: 83,
    foot: '오른발',
    joined: '2004.08.31',
    left: '2017.07.09',
    career: { apps: 559, goals: 253, assists: 146 },
    trophies: 16,
    status: 'retired',
    squad: '레전드',
    legend: true,
    radar: [
      { k: '슈팅', v: 90 },
      { k: '패스', v: 84 },
      { k: '드리블', v: 84 },
      { k: '스피드', v: 80 },
      { k: '수비', v: 60 },
      { k: '피지컬', v: 86 },
    ],
    ovr: 81,
  },
  {
    id: 'giggs',
    num: 11,
    nm: '라이언 긱스',
    en: 'Ryan Giggs',
    pos: 'MF',
    nat: '웨일스',
    flag: 'wa',
    years: '1990–2014',
    dob: '1973.11.29',
    age: 52,
    birth: '카디프, 웨일스',
    height: 180,
    weight: 67,
    foot: '왼발',
    joined: '1990.12.01',
    left: '2014.05.19',
    career: { apps: 963, goals: 168, assists: 211 },
    trophies: 34,
    status: 'retired',
    squad: '레전드',
    legend: true,
    radar: [
      { k: '슈팅', v: 80 },
      { k: '패스', v: 86 },
      { k: '드리블', v: 88 },
      { k: '스피드', v: 88 },
      { k: '수비', v: 58 },
      { k: '피지컬', v: 74 },
    ],
    ovr: 79,
  },
  {
    id: 'scholes',
    num: 18,
    nm: '폴 스콜스',
    en: 'Paul Scholes',
    pos: 'MF',
    nat: '잉글랜드',
    flag: 'gb',
    years: '1994–2013',
    dob: '1974.11.16',
    age: 51,
    birth: '솔퍼드, 잉글랜드',
    height: 170,
    weight: 70,
    foot: '오른발',
    joined: '1994.01.01',
    left: '2013.05.19',
    career: { apps: 718, goals: 155, assists: 96 },
    trophies: 25,
    status: 'retired',
    squad: '레전드',
    legend: true,
    radar: [
      { k: '슈팅', v: 84 },
      { k: '패스', v: 92 },
      { k: '드리블', v: 78 },
      { k: '스피드', v: 66 },
      { k: '수비', v: 70 },
      { k: '피지컬', v: 72 },
    ],
    ovr: 77,
  },
  {
    id: 'beckham',
    num: 7,
    nm: '데이비드 베컴',
    en: 'David Beckham',
    pos: 'MF',
    nat: '잉글랜드',
    flag: 'gb',
    years: '1992–2003',
    dob: '1975.05.02',
    age: 51,
    birth: '런던, 잉글랜드',
    height: 183,
    weight: 75,
    foot: '오른발',
    joined: '1992.07.08',
    left: '2003.07.01',
    career: { apps: 394, goals: 85, assists: 152 },
    trophies: 13,
    status: 'retired',
    squad: '레전드',
    legend: true,
    radar: [
      { k: '슈팅', v: 82 },
      { k: '패스', v: 91 },
      { k: '드리블', v: 78 },
      { k: '스피드', v: 72 },
      { k: '수비', v: 64 },
      { k: '피지컬', v: 74 },
    ],
    ovr: 77,
  },
  {
    id: 'cantona',
    num: 7,
    nm: '에리크 캉토나',
    en: 'Eric Cantona',
    pos: 'FW',
    nat: '프랑스',
    flag: 'fr',
    years: '1992–1997',
    dob: '1966.05.24',
    age: 60,
    birth: '마르세유, 프랑스',
    height: 188,
    weight: 83,
    foot: '오른발',
    joined: '1992.11.27',
    left: '1997.05.18',
    career: { apps: 185, goals: 82, assists: 50 },
    trophies: 9,
    status: 'retired',
    squad: '레전드',
    legend: true,
    radar: [
      { k: '슈팅', v: 88 },
      { k: '패스', v: 86 },
      { k: '드리블', v: 84 },
      { k: '스피드', v: 74 },
      { k: '수비', v: 50 },
      { k: '피지컬', v: 82 },
    ],
    ovr: 77,
  },
  {
    id: 'gneville',
    num: 2,
    nm: '게리 네빌',
    en: 'Gary Neville',
    pos: 'DF',
    nat: '잉글랜드',
    flag: 'gb',
    years: '1992–2011',
    dob: '1975.02.18',
    age: 51,
    birth: '베리, 잉글랜드',
    height: 180,
    weight: 75,
    foot: '오른발',
    joined: '1992.07.08',
    left: '2011.02.02',
    career: { apps: 602, goals: 7, assists: 51 },
    trophies: 20,
    status: 'retired',
    squad: '레전드',
    legend: true,
    radar: [
      { k: '슈팅', v: 40 },
      { k: '패스', v: 76 },
      { k: '드리블', v: 66 },
      { k: '스피드', v: 72 },
      { k: '수비', v: 84 },
      { k: '피지컬', v: 78 },
    ],
    ovr: 69,
  },
];

/** Synchronous lookup by `PlayerDetail.id` — the route param key. */
export function getPlayerById(id: string): PlayerDetail | undefined {
  return players.find((player) => player.id === id);
}
