import { Match } from '@entities/matches/model';
import { Standing } from '@entities/rank/model';

export const matches: Match[] = [
  {
    id: 'f1',
    month: 'M1',
    date: '3/1',
    dow: '토',
    ha: 'home',
    home: {
      teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
      code: 'MUN',
      nm: '맨체스터 유나이티드',
      score: 3,
      utd: true,
    },
    away: {
      teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
      code: 'EVE',
      nm: '에버턴',
      score: 0,
    },
    status: 'past',
    result: 'W',
    venue: '올드 트래포드',
    kickoff: '2025-03-01T15:00',
  },
  {
    id: 'f2',
    month: 'M1',
    date: '3/8',
    dow: '토',
    ha: 'away',
    home: {
      teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
      code: 'BHA',
      nm: '브라이턴',
      score: 1,
    },
    away: {
      teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
      code: 'MUN',
      nm: '맨체스터 유나이티드',
      score: 2,
      utd: true,
    },
    status: 'past',
    result: 'W',
    venue: '아멕스 스타디움',
    kickoff: '2025-03-08T20:00',
  },
  {
    id: 'f3',
    month: 'M2',
    date: '3/29',
    dow: '토',
    ha: 'home',
    home: {
      teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
      code: 'MUN',
      nm: '맨체스터 유나이티드',
      score: 1,
      utd: true,
    },
    away: {
      teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
      code: 'RMA',
      nm: '레알 마드리드',
      score: 1,
    },
    status: 'past',
    result: 'D',
    venue: '올드 트래포드',
    kickoff: '2025-03-29T20:00',
  },
  {
    id: 'f4',
    month: 'M2',
    date: '4/5',
    dow: '토',
    ha: 'away',
    home: {
      teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
      code: 'NEW',
      nm: '뉴캐슬',
      score: 1,
    },
    away: {
      teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
      code: 'MUN',
      nm: '맨체스터 유나이티드',
      score: 2,
      utd: true,
    },
    status: 'past',
    result: 'W',
    venue: '세인트 제임스 파크',
    kickoff: '2025-04-05T15:00',
  },
  {
    id: 'f5',
    month: 'M3',
    date: '5/31',
    dow: '토',
    ha: 'neutral',
    home: {
      teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
      code: 'MUN',
      nm: '맨체스터 유나이티드',
      utd: true,
    },
    away: {
      teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
      code: 'MCI',
      nm: '맨체스터 시티',
    },
    status: 'upcoming',
    time: '01:00 KST',
    venue: '웸블리 스타디움',
    kickoff: '2025-05-31T01:00',
  },
];

// ───────── Standings (순위표) ─────────
// StandingsRow·StandingsTable·StandingsTab 3개 테스트가 공유하는 fixture
// (decisions.md "StandingsTab 계열 fixture 위치" 참고). 각 엔트리는
// StandingsRow/StandingsTable/StandingsTab 테스트가 요구하는 조건(utd true/false,
// gf>ga·gf<ga, zone 5종 — D-6로 'conf'가 새로 도달 가능해짐)을 최소 1개씩
// 충족하도록 구성했다.
export const standings: Standing[] = [
  {
    teamLogoUrl: 'https://media.api-sports.io/football/teams/50.png',
    pos: 1,
    code: 'MCI',
    nm: '맨체스터 시티',
    p: 30,
    w: 25,
    d: 3,
    l: 2,
    gf: 70,
    ga: 20,
    diff: 50,
    pts: 78,
    form: ['W', 'W', 'D', 'W', 'W'],
    mv: 'same',
    zone: 'ucl',
  },
  {
    teamLogoUrl: 'https://media.api-sports.io/football/teams/49.png',
    pos: 5,
    code: 'CHE',
    nm: '첼시',
    p: 29,
    w: 17,
    d: 4,
    l: 8,
    gf: 55,
    ga: 40,
    diff: 15,
    pts: 55,
    form: ['W', 'L', 'D', 'W', 'W'],
    mv: 'same',
    zone: 'uel',
  },
  {
    teamLogoUrl: 'https://media.api-sports.io/football/teams/66.png',
    pos: 6,
    code: 'AVL',
    nm: '아스톤 빌라',
    p: 29,
    w: 15,
    d: 5,
    l: 9,
    gf: 50,
    ga: 42,
    diff: 8,
    pts: 50,
    form: ['W', 'W', 'L', 'D', 'W'],
    mv: 'same',
    zone: 'conf',
  },
  {
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    pos: 8,
    code: 'MUN',
    nm: '맨체스터 유나이티드',
    p: 29,
    w: 14,
    d: 5,
    l: 10,
    gf: 45,
    ga: 38,
    diff: 7,
    pts: 47,
    form: ['W', 'D', 'L', 'W', 'L'],
    mv: 'same',
    zone: '',
    utd: true,
  },
  {
    teamLogoUrl: 'https://media.api-sports.io/football/teams/36.png',
    pos: 15,
    code: 'FUL',
    nm: '풀럼',
    p: 29,
    w: 9,
    d: 8,
    l: 12,
    gf: 35,
    ga: 40,
    diff: -5,
    pts: 35,
    form: ['D', 'L', 'W', 'D', 'L'],
    mv: 'same',
    zone: '',
  },
  {
    teamLogoUrl: 'https://media.api-sports.io/football/teams/746.png',
    pos: 20,
    code: 'SUN',
    nm: '선덜랜드',
    p: 29,
    w: 4,
    d: 4,
    l: 21,
    gf: 20,
    ga: 60,
    diff: -40,
    pts: 16,
    form: ['L', 'L', 'D', 'L', 'L'],
    mv: 'same',
    zone: 'releg',
  },
];
