/**
 * Manchester United Hub — season page mock data (ST-01, 이슈 #29).
 *
 * Reconciled 1:1 against the design source (`.state/design-ref.md` in the
 * harness project — season.jsx + season-data.js). Values below (summary·
 * standings·zoneLegend) are copied verbatim from that spec — do not
 * hand-edit numbers/text here without re-checking the source. `subTabs` mirrors
 * the sub-tab nav described in season.jsx (component-local, not season-data.js);
 * its `en` labels are not given verbatim by the source and were chosen for this
 * migration — see result-ST-01.md for the reconciliation note.
 *
 * Seam: this is page-local mock data for the season summary/standings (UI
 * only). Match schedule data is wired to the real API (이슈 #43) — see
 * `e_entities/matches` (`getMatchScheduleList`). Standings still await
 * `e_entities/team` (`getTeamStatistics`) — see design-ref.md "백엔드 계약 갭":
 * that DTO doesn't yet carry `form`/`movement`/`zone`, so wiring it is a
 * separate issue.
 *
 * No imports from e_entities / d_features / app/api (SERVICE.md 결합도 원칙).
 */

import type {
  SeasonSummaryCard,
  Standing,
  SubTabMeta,
  ZoneLegendItem,
} from './types';

// ───────── Season summary (4) ─────────

export const seasonSummaryCards: SeasonSummaryCard[] = [
  {
    icon: 'BarChart3',
    label: '리그 순위',
    en: 'Position',
    value: '8위',
    sub: '프리미어리그',
  },
  { icon: 'Star', label: '승점', en: 'Points', value: '47', sub: '29경기' },
  {
    icon: 'Target',
    label: '득실차',
    en: 'Goal Diff',
    value: '+7',
    sub: '45득점 38실점',
  },
  {
    icon: 'Trophy',
    label: '잔여 대회',
    en: 'Active',
    value: '3개',
    sub: '리그·FA컵·UCL',
  },
];

// ───────── Standings (20) ─────────

export const standings: Standing[] = [
  {
    pos: 1,
    code: 'LIV',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '리버풀',
    p: 29,
    w: 21,
    d: 5,
    l: 3,
    gf: 64,
    ga: 26,
    pts: 68,
    form: ['W', 'W', 'W', 'D', 'W'],
    mv: 'same',
    zone: 'ucl',
  },
  {
    pos: 2,
    code: 'ARS',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '아스널',
    p: 29,
    w: 19,
    d: 7,
    l: 3,
    gf: 58,
    ga: 28,
    pts: 64,
    form: ['W', 'D', 'W', 'W', 'L'],
    mv: 'up',
    zone: 'ucl',
  },
  {
    pos: 3,
    code: 'MCI',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '맨체스터 시티',
    p: 29,
    w: 18,
    d: 6,
    l: 5,
    gf: 61,
    ga: 32,
    pts: 60,
    form: ['W', 'W', 'L', 'W', 'W'],
    mv: 'down',
    zone: 'ucl',
  },
  {
    pos: 4,
    code: 'CHE',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '첼시',
    p: 29,
    w: 16,
    d: 8,
    l: 5,
    gf: 54,
    ga: 34,
    pts: 56,
    form: ['D', 'W', 'W', 'D', 'W'],
    mv: 'up',
    zone: 'ucl',
  },
  {
    pos: 5,
    code: 'TOT',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '토트넘',
    p: 29,
    w: 16,
    d: 5,
    l: 8,
    gf: 57,
    ga: 40,
    pts: 53,
    form: ['W', 'L', 'W', 'W', 'L'],
    mv: 'down',
    zone: 'uel',
  },
  {
    pos: 6,
    code: 'NEW',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '뉴캐슬',
    p: 29,
    w: 15,
    d: 6,
    l: 8,
    gf: 52,
    ga: 38,
    pts: 51,
    form: ['W', 'W', 'D', 'L', 'W'],
    mv: 'up',
    zone: 'conf',
  },
  {
    pos: 7,
    code: 'AVL',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '아스톤 빌라',
    p: 29,
    w: 14,
    d: 7,
    l: 8,
    gf: 49,
    ga: 42,
    pts: 49,
    form: ['L', 'W', 'D', 'W', 'D'],
    mv: 'same',
    zone: '',
  },
  {
    pos: 8,
    code: 'MUN',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '맨체스터 유나이티드',
    p: 29,
    w: 13,
    d: 8,
    l: 8,
    gf: 45,
    ga: 38,
    pts: 47,
    form: ['W', 'D', 'W', 'L', 'W'],
    mv: 'up',
    zone: '',
    utd: true,
  },
  {
    pos: 9,
    code: 'BHA',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '브라이턴',
    p: 29,
    w: 12,
    d: 9,
    l: 8,
    gf: 46,
    ga: 41,
    pts: 45,
    form: ['D', 'D', 'W', 'L', 'W'],
    mv: 'down',
    zone: '',
  },
  {
    pos: 10,
    code: 'BOU',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '본머스',
    p: 29,
    w: 12,
    d: 7,
    l: 10,
    gf: 44,
    ga: 43,
    pts: 43,
    form: ['L', 'W', 'W', 'D', 'L'],
    mv: 'up',
    zone: '',
  },
  {
    pos: 11,
    code: 'FUL',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '풀럼',
    p: 29,
    w: 11,
    d: 8,
    l: 10,
    gf: 40,
    ga: 42,
    pts: 41,
    form: ['D', 'L', 'W', 'D', 'W'],
    mv: 'same',
    zone: '',
  },
  {
    pos: 12,
    code: 'CRY',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '크리스탈 팰리스',
    p: 29,
    w: 10,
    d: 9,
    l: 10,
    gf: 38,
    ga: 40,
    pts: 39,
    form: ['W', 'D', 'L', 'D', 'W'],
    mv: 'up',
    zone: '',
  },
  {
    pos: 13,
    code: 'BRE',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '브렌트포드',
    p: 29,
    w: 10,
    d: 7,
    l: 12,
    gf: 43,
    ga: 46,
    pts: 37,
    form: ['L', 'W', 'L', 'W', 'D'],
    mv: 'down',
    zone: '',
  },
  {
    pos: 14,
    code: 'EVE',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '에버턴',
    p: 29,
    w: 9,
    d: 9,
    l: 11,
    gf: 34,
    ga: 38,
    pts: 36,
    form: ['D', 'D', 'L', 'W', 'D'],
    mv: 'same',
    zone: '',
  },
  {
    pos: 15,
    code: 'WHU',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '웨스트햄',
    p: 29,
    w: 9,
    d: 7,
    l: 13,
    gf: 39,
    ga: 48,
    pts: 34,
    form: ['L', 'L', 'W', 'D', 'L'],
    mv: 'down',
    zone: '',
  },
  {
    pos: 16,
    code: 'WOL',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '울버햄튼',
    p: 29,
    w: 8,
    d: 8,
    l: 13,
    gf: 36,
    ga: 50,
    pts: 32,
    form: ['D', 'L', 'W', 'L', 'D'],
    mv: 'up',
    zone: '',
  },
  {
    pos: 17,
    code: 'NFO',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '노팅엄 포레스트',
    p: 29,
    w: 8,
    d: 6,
    l: 15,
    gf: 33,
    ga: 47,
    pts: 30,
    form: ['L', 'W', 'L', 'L', 'D'],
    mv: 'down',
    zone: '',
  },
  {
    pos: 18,
    code: 'LEI',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '레스터 시티',
    p: 29,
    w: 6,
    d: 8,
    l: 15,
    gf: 30,
    ga: 52,
    pts: 26,
    form: ['L', 'D', 'L', 'L', 'W'],
    mv: 'down',
    zone: 'releg',
  },
  {
    pos: 19,
    code: 'IPS',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '입스위치',
    p: 29,
    w: 5,
    d: 7,
    l: 17,
    gf: 28,
    ga: 58,
    pts: 22,
    form: ['L', 'L', 'D', 'L', 'L'],
    mv: 'same',
    zone: 'releg',
  },
  {
    pos: 20,
    code: 'SOU',
    teamLogoUrl: 'https://media.api-sports.io/football/teams/33.png',
    nm: '사우샘프턴',
    p: 29,
    w: 4,
    d: 6,
    l: 19,
    gf: 24,
    ga: 60,
    pts: 18,
    form: ['L', 'L', 'L', 'D', 'L'],
    mv: 'same',
    zone: 'releg',
  },
];

// ───────── Zone legend (4) ─────────

export const zoneLegend: ZoneLegendItem[] = [
  { zone: 'ucl', label: '챔피언스리그' },
  { zone: 'uel', label: '유로파리그' },
  { zone: 'conf', label: '컨퍼런스리그' },
  { zone: 'releg', label: '강등권' },
];

// ───────── Sub tabs ─────────
// Mirrors season.jsx's sub-tab nav (일정 & 결과 / 순위표). `en` labels are not
// given verbatim by season-data.js — chosen for this migration (result-ST-01.md).

export const subTabs: SubTabMeta[] = [
  { id: 'matches', kr: '일정 & 결과', en: 'Matches' },
  { id: 'table', kr: '순위표', en: 'Table' },
];
