/**
 * 선수 목록 테스트 fixture (원래 ST-2의 production mock data, PL-2로 실 API 연결 후
 * 사용자 지시에 따라 test/ 아래로 이관됨 — D-10 갱신: "삭제·이동 없이 fixture 주석만" 대신
 * 테스트 전용 데이터는 test/ 폴더에서 관리한다).
 *
 * 디자인 레퍼런스 players-data.js 기반(18명 — 1군 12 + 레전드 6). vitest의 include 패턴이
 * `*.{test,spec}.{ts,tsx}`만 수집하므로 이 파일은 테스트 스위트로 오인 수집되지 않는다.
 */

import type { PlayerListItem } from '@entities/player/model/playerListItem';

export const PLAYERS: PlayerListItem[] = [
  // ---------- current first team ----------
  {
    id: 'bruno',
    number: 8,
    name: '브루누 페르난데스',
    nameEn: 'Bruno Fernandes',
    position: 'MF',
    nationality: '포르투갈',
    flagCode: 'pt',
    years: '2020–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'rashford',
    number: 10,
    name: '마커스 래시포드',
    nameEn: 'Marcus Rashford',
    position: 'FW',
    nationality: '잉글랜드',
    flagCode: 'gb',
    years: '2015–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'hojlund',
    number: 11,
    name: '라스무스 회일룬',
    nameEn: 'Rasmus Højlund',
    position: 'FW',
    nationality: '덴마크',
    flagCode: 'dk',
    years: '2023–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'mainoo',
    number: 37,
    name: '코비 메이누',
    nameEn: 'Kobbie Mainoo',
    position: 'MF',
    nationality: '잉글랜드',
    flagCode: 'gb',
    years: '2023–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'martinez',
    number: 6,
    name: '리산드로 마르티네스',
    nameEn: 'Lisandro Martínez',
    position: 'DF',
    nationality: '아르헨티나',
    flagCode: 'ar',
    years: '2022–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'onana',
    number: 24,
    name: '안드레 오나나',
    nameEn: 'André Onana',
    position: 'GK',
    nationality: '카메룬',
    flagCode: 'cm',
    years: '2023–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'dalot',
    number: 20,
    name: '디오구 달롯',
    nameEn: 'Diogo Dalot',
    position: 'DF',
    nationality: '포르투갈',
    flagCode: 'pt',
    years: '2018–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'shaw',
    number: 23,
    name: '루크 쇼',
    nameEn: 'Luke Shaw',
    position: 'DF',
    nationality: '잉글랜드',
    flagCode: 'gb',
    years: '2014–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'casemiro',
    number: 18,
    name: '카세미루',
    nameEn: 'Casemiro',
    position: 'MF',
    nationality: '브라질',
    flagCode: 'br',
    years: '2022–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'deligt',
    number: 4,
    name: '마테이스 더 리흐트',
    nameEn: 'Matthijs de Ligt',
    position: 'DF',
    nationality: '네덜란드',
    flagCode: 'nl',
    years: '2024–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'garnacho',
    number: 17,
    name: '알레한드로 가르나초',
    nameEn: 'Alejandro Garnacho',
    position: 'FW',
    nationality: '아르헨티나',
    flagCode: 'ar',
    years: '2020–현재',
    status: 'active',
    squad: '1군',
  },
  {
    id: 'mount',
    number: 7,
    name: '메이슨 마운트',
    nameEn: 'Mason Mount',
    position: 'MF',
    nationality: '잉글랜드',
    flagCode: 'gb',
    years: '2023–현재',
    status: 'active',
    squad: '1군',
  },

  // ---------- legends (retired) ----------
  {
    id: 'rooney',
    number: 10,
    name: '웨인 루니',
    nameEn: 'Wayne Rooney',
    position: 'FW',
    nationality: '잉글랜드',
    flagCode: 'gb',
    years: '2004–2017',
    status: 'retired',
    squad: '레전드',
  },
  {
    id: 'giggs',
    number: 11,
    name: '라이언 긱스',
    nameEn: 'Ryan Giggs',
    position: 'MF',
    nationality: '웨일스',
    flagCode: 'wa',
    years: '1990–2014',
    status: 'retired',
    squad: '레전드',
  },
  {
    id: 'scholes',
    number: 18,
    name: '폴 스콜스',
    nameEn: 'Paul Scholes',
    position: 'MF',
    nationality: '잉글랜드',
    flagCode: 'gb',
    years: '1994–2013',
    status: 'retired',
    squad: '레전드',
  },
  {
    id: 'beckham',
    number: 7,
    name: '데이비드 베컴',
    nameEn: 'David Beckham',
    position: 'MF',
    nationality: '잉글랜드',
    flagCode: 'gb',
    years: '1992–2003',
    status: 'retired',
    squad: '레전드',
  },
  {
    id: 'cantona',
    number: 7,
    name: '에리크 캉토나',
    nameEn: 'Eric Cantona',
    position: 'FW',
    nationality: '프랑스',
    flagCode: 'fr',
    years: '1992–1997',
    status: 'retired',
    squad: '레전드',
  },
  {
    id: 'gneville',
    number: 2,
    name: '게리 네빌',
    nameEn: 'Gary Neville',
    position: 'DF',
    nationality: '잉글랜드',
    flagCode: 'gb',
    years: '1992–2011',
    status: 'retired',
    squad: '레전드',
  },
];
